### ISSUE TITLE
Can you add a TrueHD Audio (atmos) plus nuclear power (AC3 core) in behappy

### ISSUE THREAD

**Issue by KSSW** [jones1913/BeHappy#1]
Can you add a TrueHD Audio (_atmos_) plus nuclear power (_AC3 core_) in behappy Audio core with TrueHD and Atmos

**Comment by KSSW** [comment]
Add options AC3 5.1 Dolby Surround mod or Dolby Surround ex mod, and AC3 2.0 Dolby Surround mod or Dolby Headphone mod to the core

**Comment by KSSW** [comment]
Why is there no ffmpge AC3 Dolby Headphone mod code in ffmpge

**Comment by jones1913** [comment]
I'm not actively working on this anymore. Your best chance is to ask in doom9's forum BeHappy thread if somebody can add these things to an extension.

--> https://forum.doom9.org/showthread.php?t=104686&page=65
